CREATE TABLE "KEHONOSA_LOOKUP" 
   (	"KEHONOSA_ID" NUMBER NOT NULL ENABLE, 
	"KEHONOSA" VARCHAR2(40) NOT NULL ENABLE, 
	 PRIMARY KEY ("KEHONOSA_ID")
  USING INDEX  ENABLE
   ) ;

CREATE TABLE "LIIKE" 
   (	"ID" NUMBER DEFAULT ON NULL "APEXI"."LIIKE_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"NIMI" VARCHAR2(50 CHAR), 
	"KUVA" BLOB, 
	"KUVA_FILENAME" VARCHAR2(512 CHAR), 
	"KUVA_MIMETYPE" VARCHAR2(512 CHAR), 
	"KUVA_CHARSET" VARCHAR2(512 CHAR), 
	"KUVA_LASTUPD" DATE, 
	"LINKKI" VARCHAR2(200), 
	"KEHONPAINOLIIKE" NUMBER(1,0), 
	"SELITE" VARCHAR2(300), 
	"KEHONOSA_ID" NUMBER, 
	 CONSTRAINT "LIIKE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

CREATE TABLE "HENKILO" 
   (	"ID" NUMBER DEFAULT ON NULL "APEXI"."HENKILO_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"NIMI" VARCHAR2(10 CHAR), 
	"PAINO" NUMBER, 
	 CONSTRAINT "HENKILO_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

CREATE TABLE "TREENI" 
   (	"HENKILO_ID" NUMBER, 
	"ID" NUMBER DEFAULT ON NULL "APEXI"."TREENI_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"KUVAUS" VARCHAR2(40), 
	"AKTIIVINEN" NUMBER(1,0), 
	"MESO_ID" NUMBER, 
	"BLOCK" NUMBER, 
	"BLOCK_TREENI_NRO" NUMBER, 
	 CONSTRAINT "TREENI_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

CREATE TABLE "TREENIKERTA" 
   (	"TREENI_ID" NUMBER, 
	"HENKILO_ID" NUMBER, 
	"ID" NUMBER DEFAULT ON NULL "APEXI"."TREENIKERTA_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"LIIKE" NUMBER, 
	"RIR" NUMBER(2,0), 
	"SARJANUMERO" NUMBER(2,0), 
	"KG" NUMBER, 
	"TOISTOT" NUMBER(2,0), 
	"PVM" DATE, 
	"DELOAD" NUMBER, 
	"TREENIN_KERTA" NUMBER, 
	"MESO_ID" NUMBER, 
	"BLOCK" NUMBER, 
	"BLOCK_TREENI_NRO" NUMBER, 
	 CONSTRAINT "TREENIKERTA_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

CREATE TABLE "TREENILIIKE" 
   (	"TREENI_ID" NUMBER, 
	"LIIKE_ID" NUMBER, 
	"ID" NUMBER DEFAULT ON NULL "APEXI"."TREENILIIKE_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"RIR" VARCHAR2(20), 
	"SARJAKUVAUS" VARCHAR2(20 CHAR), 
	"SARJAT" NUMBER, 
	"TOISTOT" VARCHAR2(10 CHAR), 
	"JARJESTYS" NUMBER, 
	 CONSTRAINT "TREENILIIKE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

ALTER TABLE "LIIKE" ADD FOREIGN KEY ("KEHONOSA_ID")
	  REFERENCES "KEHONOSA_LOOKUP" ("KEHONOSA_ID") ENABLE;

ALTER TABLE "TREENI" ADD CONSTRAINT "TREENI_HENKILO_ID_FK" FOREIGN KEY ("HENKILO_ID")
	  REFERENCES "HENKILO" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "TREENILIIKE" ADD CONSTRAINT "TREENILIIKE_TREENI_ID_FK" FOREIGN KEY ("TREENI_ID")
	  REFERENCES "TREENI" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "TREENILIIKE" ADD CONSTRAINT "TREENILIIKE_LIIKE_ID_FK" FOREIGN KEY ("LIIKE_ID")
	  REFERENCES "LIIKE" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "TREENIKERTA" ADD CONSTRAINT "TREENIKERTA_TREENI_ID_FK" FOREIGN KEY ("TREENI_ID")
	  REFERENCES "TREENI" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "TREENIKERTA" ADD CONSTRAINT "TREENIKERTA_HENKILO_ID_FK" FOREIGN KEY ("HENKILO_ID")
	  REFERENCES "HENKILO" ("ID") ON DELETE CASCADE ENABLE;

ALTER TABLE "TREENIKERTA" ADD CONSTRAINT "TREENIKERTA_LIIKE_FK" FOREIGN KEY ("LIIKE")
	  REFERENCES "LIIKE" ("ID") ON DELETE CASCADE ENABLE;

CREATE INDEX "TREENI_I1" ON "TREENI" ("HENKILO_ID") 
  ;

CREATE INDEX "TREENIKERTA_I1" ON "TREENIKERTA" ("HENKILO_ID") 
  ;

CREATE INDEX "TREENIKERTA_I152" ON "TREENIKERTA" ("LIIKE") 
  ;

CREATE INDEX "TREENIKERTA_I163" ON "TREENIKERTA" ("TREENI_ID") 
  ;

CREATE INDEX "TREENILIIKE_I1" ON "TREENILIIKE" ("LIIKE_ID") 
  ;

CREATE INDEX "TREENILIIKE_I92" ON "TREENILIIKE" ("TREENI_ID") 
  ;

CREATE OR REPLACE EDITIONABLE TRIGGER "T_KEHONOSA_LOOKUP" before insert or update on "KEHONOSA_LOOKUP" for each row begin if inserting and :new."KEHONOSA_ID" is null then 
  for c1 in (select "KEHONOSA_LOOKUP_SEQ".nextval nv from dual) loop 
     :new."KEHONOSA_ID" := c1.nv;   end loop; end if; end;

/


ALTER TRIGGER "T_KEHONOSA_LOOKUP" ENABLE;

